<?php

namespace Modules\Paypal\Filament\Resources;

use Filament\Forms;
use Filament\Forms\Form;
use Filament\Tables;
use Filament\Tables\Table;
use Modules\Base\Filament\Resources\BaseResource;
use Modules\Paypal\Filament\Resources\IpnResource\Pages;
use Modules\Paypal\Models\Ipn;

class IpnResource extends BaseResource
{
    protected static ?string $model = Ipn::class;

    protected static ?string $slug = 'paypal/ipn';

    protected static ?string $navigationGroup = 'Account';

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    protected static ?string $navigationParentItem = 'Gateway';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('business')
                    ->required()
                    ->maxLength(127),
                Forms\Components\TextInput::make('charset')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('custom')
                    ->required()
                    ->maxLength(256),
                Forms\Components\TextInput::make('notify_version')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('parent_txn_id')
                    ->required()
                    ->maxLength(19),
                Forms\Components\TextInput::make('receiver_email')
                    ->email()
                    ->required()
                    ->maxLength(254),
                Forms\Components\TextInput::make('receiver_id')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('residence_country')
                    ->required()
                    ->maxLength(2),
                Forms\Components\Toggle::make('test_ipn')
                    ->required(),
                Forms\Components\TextInput::make('txn_id')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('txn_type')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('verify_sign')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('address_country')
                    ->required()
                    ->maxLength(64),
                Forms\Components\TextInput::make('address_city')
                    ->required()
                    ->maxLength(40),
                Forms\Components\TextInput::make('address_country_code')
                    ->required()
                    ->maxLength(64),
                Forms\Components\TextInput::make('address_name')
                    ->required()
                    ->maxLength(128),
                Forms\Components\TextInput::make('address_state')
                    ->required()
                    ->maxLength(40),
                Forms\Components\TextInput::make('address_status')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('address_street')
                    ->required()
                    ->maxLength(200),
                Forms\Components\TextInput::make('address_zip')
                    ->required()
                    ->maxLength(20),
                Forms\Components\TextInput::make('contact_phone')
                    ->tel()
                    ->required()
                    ->maxLength(20),
                Forms\Components\TextInput::make('first_name')
                    ->required()
                    ->maxLength(64),
                Forms\Components\TextInput::make('last_name')
                    ->required()
                    ->maxLength(64),
                Forms\Components\TextInput::make('payer_business_name')
                    ->required()
                    ->maxLength(127),
                Forms\Components\TextInput::make('payer_email')
                    ->email()
                    ->required()
                    ->maxLength(127),
                Forms\Components\TextInput::make('payer_id')
                    ->required()
                    ->maxLength(13),
                Forms\Components\TextInput::make('auth_amount')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('auth_exp')
                    ->required()
                    ->maxLength(28),
                Forms\Components\TextInput::make('auth_id')
                    ->required()
                    ->maxLength(19),
                Forms\Components\TextInput::make('auth_status')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('exchange_rate')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('invoice')
                    ->required()
                    ->maxLength(127),
                Forms\Components\TextInput::make('item_name')
                    ->required()
                    ->maxLength(127),
                Forms\Components\TextInput::make('item_number')
                    ->required()
                    ->maxLength(127),
                Forms\Components\TextInput::make('mc_currency')
                    ->required()
                    ->maxLength(32),
                Forms\Components\TextInput::make('mc_fee')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('mc_gross')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('mc_handling')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('mc_shipping')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('memo')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('num_cart_items')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('option_name1')
                    ->required()
                    ->maxLength(64),
                Forms\Components\TextInput::make('option_name2')
                    ->required()
                    ->maxLength(64),
                Forms\Components\TextInput::make('payer_status')
                    ->required()
                    ->maxLength(255),
                Forms\Components\DateTimePicker::make('payment_date'),
                Forms\Components\TextInput::make('payment_gross')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('payment_status')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('payment_type')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('pending_reason')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('protection_eligibility')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('quantity')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('reason_code')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('remaining_settle')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('settle_amount')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('settle_currency')
                    ->required()
                    ->maxLength(32),
                Forms\Components\TextInput::make('shipping')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('shipping_method')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('tax')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('transaction_entity')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('auction_buyer_id')
                    ->required()
                    ->maxLength(64),
                Forms\Components\DateTimePicker::make('auction_closing_date'),
                Forms\Components\TextInput::make('auction_multi_item')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('for_auction')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('amount')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('amount_per_cycle')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('initial_payment_amount')
                    ->numeric()
                    ->default(null),
                Forms\Components\DateTimePicker::make('next_payment_date'),
                Forms\Components\TextInput::make('outstanding_balance')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('payment_cycle')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('period_type')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('product_name')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('product_type')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('profile_status')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('recurring_payment_id')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('rp_invoice_id')
                    ->required()
                    ->maxLength(127),
                Forms\Components\DateTimePicker::make('time_created'),
                Forms\Components\TextInput::make('amount1')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('amount2')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('amount3')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('mc_amount1')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('mc_amount2')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('mc_amount3')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('password')
                    ->password()
                    ->required()
                    ->maxLength(24),
                Forms\Components\TextInput::make('period1')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('period2')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('period3')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('reattempt')
                    ->required()
                    ->maxLength(1),
                Forms\Components\TextInput::make('recur_times')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('recurring')
                    ->required()
                    ->maxLength(1),
                Forms\Components\DateTimePicker::make('retry_at'),
                Forms\Components\DateTimePicker::make('subscr_date'),
                Forms\Components\DateTimePicker::make('subscr_effective'),
                Forms\Components\TextInput::make('subscr_id')
                    ->required()
                    ->maxLength(19),
                Forms\Components\TextInput::make('username')
                    ->required()
                    ->maxLength(64),
                Forms\Components\DateTimePicker::make('case_creation_date'),
                Forms\Components\TextInput::make('case_id')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('case_type')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('receipt_id')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('currency_code')
                    ->required()
                    ->maxLength(32),
                Forms\Components\TextInput::make('handling_amount')
                    ->numeric()
                    ->default(null),
                Forms\Components\TextInput::make('transaction_subject')
                    ->required()
                    ->maxLength(256),
                Forms\Components\TextInput::make('ipaddress')
                    ->maxLength(39)
                    ->default(null),
                Forms\Components\Toggle::make('flag')
                    ->required(),
                Forms\Components\TextInput::make('flag_code')
                    ->required()
                    ->maxLength(16),
                Forms\Components\Textarea::make('flag_info')
                    ->required()
                    ->columnSpanFull(),
                Forms\Components\Textarea::make('query')
                    ->required()
                    ->columnSpanFull(),
                Forms\Components\Textarea::make('response')
                    ->required()
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('from_view')
                    ->maxLength(6)
                    ->default(null),
                Forms\Components\TextInput::make('mp_id')
                    ->maxLength(128)
                    ->default(null),
                Forms\Components\TextInput::make('option_selection1')
                    ->required()
                    ->maxLength(200),
                Forms\Components\TextInput::make('option_selection2')
                    ->required()
                    ->maxLength(200),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('business')
                    ->searchable(),
                Tables\Columns\TextColumn::make('charset')
                    ->searchable(),
                Tables\Columns\TextColumn::make('custom')
                    ->searchable(),
                Tables\Columns\TextColumn::make('notify_version')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('parent_txn_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('receiver_email')
                    ->searchable(),
                Tables\Columns\TextColumn::make('receiver_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('residence_country')
                    ->searchable(),
                Tables\Columns\IconColumn::make('test_ipn')
                    ->boolean(),
                Tables\Columns\TextColumn::make('txn_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('txn_type')
                    ->searchable(),
                Tables\Columns\TextColumn::make('verify_sign')
                    ->searchable(),
                Tables\Columns\TextColumn::make('address_country')
                    ->searchable(),
                Tables\Columns\TextColumn::make('address_city')
                    ->searchable(),
                Tables\Columns\TextColumn::make('address_country_code')
                    ->searchable(),
                Tables\Columns\TextColumn::make('address_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('address_state')
                    ->searchable(),
                Tables\Columns\TextColumn::make('address_status')
                    ->searchable(),
                Tables\Columns\TextColumn::make('address_street')
                    ->searchable(),
                Tables\Columns\TextColumn::make('address_zip')
                    ->searchable(),
                Tables\Columns\TextColumn::make('contact_phone')
                    ->searchable(),
                Tables\Columns\TextColumn::make('first_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('last_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('payer_business_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('payer_email')
                    ->searchable(),
                Tables\Columns\TextColumn::make('payer_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('auth_amount')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('auth_exp')
                    ->searchable(),
                Tables\Columns\TextColumn::make('auth_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('auth_status')
                    ->searchable(),
                Tables\Columns\TextColumn::make('exchange_rate')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('invoice')
                    ->searchable(),
                Tables\Columns\TextColumn::make('item_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('item_number')
                    ->searchable(),
                Tables\Columns\TextColumn::make('mc_currency')
                    ->searchable(),
                Tables\Columns\TextColumn::make('mc_fee')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('mc_gross')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('mc_handling')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('mc_shipping')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('memo')
                    ->searchable(),
                Tables\Columns\TextColumn::make('num_cart_items')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('option_name1')
                    ->searchable(),
                Tables\Columns\TextColumn::make('option_name2')
                    ->searchable(),
                Tables\Columns\TextColumn::make('payer_status')
                    ->searchable(),
                Tables\Columns\TextColumn::make('payment_date')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('payment_gross')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('payment_status')
                    ->searchable(),
                Tables\Columns\TextColumn::make('payment_type')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pending_reason')
                    ->searchable(),
                Tables\Columns\TextColumn::make('protection_eligibility')
                    ->searchable(),
                Tables\Columns\TextColumn::make('quantity')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('reason_code')
                    ->searchable(),
                Tables\Columns\TextColumn::make('remaining_settle')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('settle_amount')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('settle_currency')
                    ->searchable(),
                Tables\Columns\TextColumn::make('shipping')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('shipping_method')
                    ->searchable(),
                Tables\Columns\TextColumn::make('tax')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('transaction_entity')
                    ->searchable(),
                Tables\Columns\TextColumn::make('auction_buyer_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('auction_closing_date')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('auction_multi_item')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('for_auction')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('amount')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('amount_per_cycle')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('initial_payment_amount')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('next_payment_date')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('outstanding_balance')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('payment_cycle')
                    ->searchable(),
                Tables\Columns\TextColumn::make('period_type')
                    ->searchable(),
                Tables\Columns\TextColumn::make('product_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('product_type')
                    ->searchable(),
                Tables\Columns\TextColumn::make('profile_status')
                    ->searchable(),
                Tables\Columns\TextColumn::make('recurring_payment_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('rp_invoice_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('time_created')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('amount1')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('amount2')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('amount3')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('mc_amount1')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('mc_amount2')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('mc_amount3')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('period1')
                    ->searchable(),
                Tables\Columns\TextColumn::make('period2')
                    ->searchable(),
                Tables\Columns\TextColumn::make('period3')
                    ->searchable(),
                Tables\Columns\TextColumn::make('reattempt')
                    ->searchable(),
                Tables\Columns\TextColumn::make('recur_times')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('recurring')
                    ->searchable(),
                Tables\Columns\TextColumn::make('retry_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('subscr_date')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('subscr_effective')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('subscr_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('username')
                    ->searchable(),
                Tables\Columns\TextColumn::make('case_creation_date')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('case_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('case_type')
                    ->searchable(),
                Tables\Columns\TextColumn::make('receipt_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('currency_code')
                    ->searchable(),
                Tables\Columns\TextColumn::make('handling_amount')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('transaction_subject')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ipaddress')
                    ->searchable(),
                Tables\Columns\IconColumn::make('flag')
                    ->boolean(),
                Tables\Columns\TextColumn::make('flag_code')
                    ->searchable(),
                Tables\Columns\TextColumn::make('from_view')
                    ->searchable(),
                Tables\Columns\TextColumn::make('mp_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('option_selection1')
                    ->searchable(),
                Tables\Columns\TextColumn::make('option_selection2')
                    ->searchable(),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                Tables\Filters\TrashedFilter::make(),
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                    Tables\Actions\ForceDeleteBulkAction::make(),
                    Tables\Actions\RestoreBulkAction::make(),
                ]),
            ]);
    }

    public static function getPages(): array
    {

        return [
            'index' => Pages\Listing::route('/'),
            'create' => Pages\Creating::route('/create'),
            'edit' => Pages\Editing::route('/{record}/edit'),
        ];
    }
}
